### ISSUE TITLE
Misleading Readme

### ISSUE THREAD

**Issue by willymwai** [muth0mi/muth0mi.github.io#1]
## Expected Behavior

coderoly.github.io to render the content of index.html from the repo

## Current Behavior

coderoly.github.io displays the error below
![image](https://user-images.githubusercontent.com/3677734/107608723-cd71c900-6c4d-11eb-8b16-e6605f432f54.png)

## Possible Solution

Replace coderoly.github.io with muth0mi.github.io on the Readme

## Steps to Reproduce

1. Click New Tab on your browser
2. Paste coderoly.github.io on the address bar then press enter
3. Sip on some coffee as your browser figures out some internet stuff
4. Get shocked by the error page and spill coffee on your clean pants

## Context (Environment)

I as the user would like to access the page without spilling coffee on my pants as a result of shock

## Detailed Description

Replace coderoly.github.io with muth0mi.github.io on the Readme so that users don't spill coffee on their clean pants

## Possible Implementation

Open Readme on the text editor, Replace coderoly.github.io with muth0mi.github.io. I'll be happy to open a PR

**Comment by muth0mi** [comment]
"The maintainer of this repo is currently caught up with other things. You are welcome to create a PR. He will review and merge within 2 to 3 months."
